export const LANGUAGES_ARRAY = [
    'ALL',
    'ENGLISH',
    'SPANISH',
    'FRENCH',
    'GERMAN',
    'ITALIAN',
    'PORTUGUESE',
    'ROMANIAN',
    'SWEDISH',
    'DUTCH',
    'FINNISH',
    'NORWEGIAN',
    'POLISH',
    'HUNGARIAN',
];
